# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codeRuntime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63odeRuntime.proto\")\n\nRunRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\">\n\rSubmitRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x1f\n\x0ctestCaseList\x18\x02 \x03(\x0b\x32\t.TestCase\"-\n\x0bRunResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x0e\n\x06stdout\x18\x02 \x01(\t\"/\n\x0eSubmitResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0e\n\x06output\x18\x02 \x01(\t\"(\n\x08TestCase\x12\r\n\x05score\x18\x01 \x01(\x05\x12\r\n\x05input\x18\x02 \x01(\t2f\n\x0b\x43odeRuntime\x12&\n\x07RunCode\x12\x0b.RunRequest\x1a\x0c.RunResponse\"\x00\x12/\n\nSubmitCode\x12\x0e.SubmitRequest\x1a\x0f.SubmitResponse\"\x00\x42>\n\x1d\x63om.litcode.server.grpcClientB\x10\x43odeRuntimeProtoP\x01\x88\x01\x01\xa2\x02\x05\x43\x44RUNb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codeRuntime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.litcode.server.grpcClientB\020CodeRuntimeProtoP\001\210\001\001\242\002\005CDRUN'
  _RUNREQUEST._serialized_start=21
  _RUNREQUEST._serialized_end=62
  _SUBMITREQUEST._serialized_start=64
  _SUBMITREQUEST._serialized_end=126
  _RUNRESPONSE._serialized_start=128
  _RUNRESPONSE._serialized_end=173
  _SUBMITRESPONSE._serialized_start=175
  _SUBMITRESPONSE._serialized_end=222
  _TESTCASE._serialized_start=224
  _TESTCASE._serialized_end=264
  _CODERUNTIME._serialized_start=266
  _CODERUNTIME._serialized_end=368
# @@protoc_insertion_point(module_scope)
