# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pythonRuntime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pythonRuntime.proto\")\n\nRunRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\">\n\rSubmitRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x1f\n\x0ctestCaseList\x18\x02 \x03(\x0b\x32\t.TestCase\"\x1d\n\x0bRunResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\"/\n\x0eSubmitResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0e\n\x06output\x18\x02 \x01(\t\"(\n\x08TestCase\x12\r\n\x05score\x18\x01 \x01(\x05\x12\r\n\x05input\x18\x02 \x01(\t2e\n\nCodingTest\x12&\n\x07RunCode\x12\x0b.RunRequest\x1a\x0c.RunResponse\"\x00\x12/\n\nSubmitCode\x12\x0e.SubmitRequest\x1a\x0f.SubmitResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pythonRuntime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RUNREQUEST._serialized_start=23
  _RUNREQUEST._serialized_end=64
  _SUBMITREQUEST._serialized_start=66
  _SUBMITREQUEST._serialized_end=128
  _RUNRESPONSE._serialized_start=130
  _RUNRESPONSE._serialized_end=159
  _SUBMITRESPONSE._serialized_start=161
  _SUBMITRESPONSE._serialized_end=208
  _TESTCASE._serialized_start=210
  _TESTCASE._serialized_end=250
  _CODINGTEST._serialized_start=252
  _CODINGTEST._serialized_end=353
# @@protoc_insertion_point(module_scope)
