version: "3"

services:
  litcode-api:
    image: litcode-api
    # build: .
    container_name: litcode-api
    ports:
      - 3003:3003
    networks:
      - litcode
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://litcode-db:3306/litcodedb
      - JS_GRPC_URL=litcode-js
      - JS_GRPC_PORT=50052

networks:
  litcode:
    name: litcode
